sudo: required
services:
- docker
env:
  global:
  - SHA=$(git rev-parse HEAD)
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - USE_DATABASE=sqlite

before_install:
- openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null;
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components update kubectl
- gcloud auth activate-service-account --key-file service-account.json
- gcloud config set project saurl-256606
- gcloud config set compute/zone asia-east1-a
- gcloud container clusters get-credentials saurl-cluster
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t tzuhsuanhuang/saurl-client-test -f ./client/Dockerfile.dev ./client
- docker build -t tzuhsuanhuang/saurl-api-test -f ./api/Dockerfile.dev ./api

script:
- docker run -e CI=true tzuhsuanhuang/saurl-client-test yarn test
- docker run -e CI=true -e DJANGO_SECRET_KEY -e USE_DATABASE tzuhsuanhuang/saurl-api-test python manage.py test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master