version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
    - '16384:80'
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes:
    - ./api:/app
    - ./api/keys:/app/keys
    env_file:
    - ./api/.env
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
    - /app/node_modules
    - ./client:/app