version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
    - '16384:80'
  api:
    image: tzuhsuanhuang/saurl-api:sqlite3
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
    - /app/node_modules
    - ./client:/app