version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    ports:
    - "16384:8000"
    volumes:
      - ./api:/app
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
    - "16385:8000"
    volumes:
    - /app/node_modules
    - ./client:/app