apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: saurl-io-tls
spec:
  secretName: saurl-io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: saurl.io
  dnsNames:
  - saurl.io
  - www.saurl.io
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - saurl.io
      - www.saurl.io